### ISSUE TITLE
Blurred projecting image

### ISSUE THREAD

**Issue by GuangWei-Zhang** [HarveyLab/mouseVR#4]
I tested using the exact setup, however, I found that the image is kinda blurred after been reflected by the mirror. Have you guys had this problem and how to solve it? I am thinking about using a monitor as another option.

**Comment by noahpettit** [comment]
Hi. Are you using a first-surface mirror? If not, the image will be slightly blurred as the image is reflected twice - once by the surface of the glass and again by the coated surface. If you are using a first-surface mirror, make sure to have the coated side facing towards the projector. The mirror will look mirrored on both sides but only one side is coated - you can tell which side is coated by placing your finger on the surface and seeing if there is a gap between the object touching the surface and the reflection. If there is, the opposite side is coated.

**Comment by noahpettit** [comment]
I am closing this issue. If you still have issues, please open a new issue or send me an email. gl with experiments!
