### ISSUE TITLE
Video of MouseVR

### ISSUE THREAD

**Issue by alexschultze** [HarveyLab/mouseVR#5]
Honestly interesting project, was interested to see some in action video.
Would recommend to add a video to the Readme. 
(As well as a link to your website which is missing)

Is that your project?
https://www.youtube.com/watch?v=1DJOTEDBA2c

**Comment by noahpettit** [comment]
Thanks for your interest! I've added the link and I will consider adding a video.

The video you linked is of one of the original mouse VR designs developed in David Tank's lab, where Christopher Harvey was a postdoc. When Chris set up his lab we switched to a cylindrical screen w/ back projection, which was further optimized and miniaturized into this version.
